### ISSUE TITLE
Group capstone:: set up your Kanban board

### ISSUE THREAD

**Issue by Abbas-Aljuaifari** [Log-benjamin/Microverse-Javascript-Capstone#41]
https://github.com/Log-benjamin/Microverse-Javascript-Capstone

**Comment by Gambit142** [comment]
Hi @Abbas-Aljuaifari @Log-benjamin 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- Kindly include the details and GitHub handles of the people working on this project. 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
